CREATE TABLE IF NOT EXISTS cifra_santa_importacao_fonte (
 slug VARCHAR(40) CHARACTER SET ascii NOT NULL PRIMARY KEY,
 nome VARCHAR(80) NOT NULL,
 habilitada TINYINT(1) NOT NULL DEFAULT 0,
 configuracao MEDIUMTEXT NOT NULL,
 atualizado_por BIGINT UNSIGNED NOT NULL,
 criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 FOREIGN KEY (atualizado_por) REFERENCES cifra_santa_usuario(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
