<div class="sr-reader" data-reader data-original-key="D">
    <header class="sr-topbar">
        <a href="<?= e(url('/')) ?>" class="sr-brand" aria-label="Cifra Santa, início"><span class="sr-brand-icon"><?= lit_icon('mark',22) ?></span><span>Cifra <strong>Santa</strong><small>MÚSICA PARA SERVIR</small></span></a>
        <nav class="sr-crumbs" aria-label="Caminho"><a href="<?= e(url('/buscar')) ?>">Biblioteca</a><span>/</span><span><?= e($song['title']) ?></span></nav>
        <div class="sr-top-actions"><button type="button" data-action="download" aria-label="Baixar cifra em texto" title="Baixar cifra"><?= icon('download',18) ?></button><button type="button" data-action="print" aria-label="Imprimir cifra" title="Imprimir"><?= icon('print',18) ?></button><button type="button" class="<?= is_favorite($song['id']) ? 'is-active' : '' ?>" data-favorite-id="<?= e($song['id']) ?>" aria-label="<?= is_favorite($song['id']) ? 'Remover dos favoritos' : 'Adicionar aos favoritos' ?>" title="Favorito"><?= icon('heart',18) ?></button></div>
    </header>
    <div class="sr-layout">
        <section class="sr-hero" aria-labelledby="sr-song-title"><div class="sr-hero-glow" aria-hidden="true">✳</div><a href="<?= e(url('/buscar')) ?>" class="sr-back"><?= icon('arrow',16) ?> Voltar à biblioteca</a><span class="sr-kicker"><i></i> CIFRA SANTA · REPERTÓRIO CATÓLICO</span><h1 id="sr-song-title"><?= e($song['title']) ?></h1><p><?= e($song['artist']) ?> <span>·</span> Violão e guitarra</p><div class="sr-meta"><span>Tom original <b>D</b></span><span>Tom atual <b data-key-display>D</b></span><span>Afinação <b>Padrão</b></span></div></section>
        <aside class="sr-panel" aria-label="Painel de execução">
            <button type="button" class="sr-panel-head" data-action="panel" aria-expanded="false"><span class="sr-panel-icon"><?= icon('sliders',19) ?></span><span class="sr-panel-title"><strong>Seu palco</strong><small>Ajuste a cifra ao seu jeito</small></span><span class="sr-panel-chevron"><?= icon('chevron',18) ?></span></button>
            <div class="sr-mobile-quick"><div class="sr-stepper"><button type="button" data-action="key-down" aria-label="Diminuir tom">−</button><b data-key-display>D</b><button type="button" data-action="key-up" aria-label="Aumentar tom">+</button></div><button type="button" data-action="scroll" aria-pressed="false"><?= icon('play',15) ?> Rolagem</button><button type="button" data-action="diagrams" aria-pressed="true"><?= icon('book',15) ?> Acordes</button></div>
            <div class="sr-panel-body">
                <div class="sr-panel-group"><span class="sr-group-label">EXECUÇÃO</span><div class="sr-toggle-grid"><button type="button" data-action="scroll" aria-pressed="false"><?= icon('play',17) ?><strong>Rolagem</strong><small data-scroll-label>Automática</small></button><button type="button" data-action="metronome" aria-pressed="false"><?= icon('clock',17) ?><strong>Metrônomo</strong><small data-metronome-label>Marcar tempo</small></button></div></div>
                <div class="sr-panel-group"><span class="sr-group-label">HARMONIA</span><div class="sr-setting"><span>Tom <small>Transpor acordes</small></span><div class="sr-stepper"><button type="button" data-action="key-down" aria-label="Diminuir tom">−</button><b data-key-display>D</b><button type="button" data-action="key-up" aria-label="Aumentar tom">+</button></div></div><div class="sr-setting"><span>Capotraste <small>Posição de referência</small></span><div class="sr-stepper"><button type="button" data-action="capo-down" aria-label="Diminuir capotraste">−</button><b data-capo-display>0</b><button type="button" data-action="capo-up" aria-label="Aumentar capotraste">+</button></div></div><div class="sr-setting"><span>Andamento <small>Batidas por minuto</small></span><div class="sr-stepper"><button type="button" data-action="bpm-down" aria-label="Diminuir andamento">−</button><b data-bpm-display>80</b><button type="button" data-action="bpm-up" aria-label="Aumentar andamento">+</button></div></div></div>
                <div class="sr-panel-group"><span class="sr-group-label">LEITURA</span><div class="sr-setting"><span>Tamanho do texto <small data-font-display>100%</small></span><div class="sr-stepper"><button type="button" data-action="font-down" aria-label="Diminuir texto">−</button><b>Aa</b><button type="button" data-action="font-up" aria-label="Aumentar texto">+</button></div></div><button type="button" class="sr-switch-row" data-action="diagrams" aria-pressed="true"><span><?= icon('book',17) ?> Diagramas de acordes</span><b class="on" data-diagram-label>Exibir</b></button><button type="button" class="sr-switch-row" data-action="columns" aria-pressed="false"><span><?= icon('list',17) ?> Duas colunas</span><b data-columns-label>Desligado</b></button></div>
            </div><p class="sr-panel-foot">Feito para acompanhar você do ensaio ao altar.</p>
        </aside>
        <main class="sr-sheet"><div class="sr-sheet-head"><div><span class="sr-sheet-eyebrow">LEITURA MUSICAL</span><h2>Cifra e letra</h2></div><span class="sr-preview-tag">TRECHO DE PRÉVIA</span></div>
            <div class="diagram-strip" data-diagram-strip aria-label="Diagramas de acordes"><?php foreach ($shapes as $name=>$fingering) partial('chord-diagram', compact('name','fingering')); ?></div>
            <p class="reader-diagram-note" data-diagram-note hidden>Diagramas disponíveis no tom original D. Os acordes no texto foram transpostos para <span data-key-display>D</span>.</p>
            <p class="reader-mobile-hint">Deslize a cifra para os lados para acompanhar os acordes.</p>
            <div class="reference-chart" data-chart><?php foreach ($chart as $line): ?><div class="chart-pair <?= !empty($line[2]) ? 'section-start' : '' ?>"><div class="chart-chords" data-chords><?= e($line[0]) ?></div><div class="chart-lyrics"><?= e($line[1]) ?></div></div><?php endforeach; ?></div>
            <div class="reader-end-note"><?= icon('spark',18) ?><span>Trecho presente no print enviado. Envie a continuação para completar esta versão no leitor.</span></div>
        </main>
    </div>
</div>
